spring.application.name=foundite
server.port=8080

# PostgreSQL (La connexion à la base de données Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/founditedb
spring.datasource.username=foundite
spring.datasource.password=foundite123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf (Pour que tes modifications HTML s'affichent vite)
spring.thymeleaf.cache=false

# Ton accès temporaire pour tester le Frontend
spring.security.user.name=admin
spring.security.user.password=1234